### ISSUE TITLE
Queue up multiple animations

### ISSUE THREAD

**Issue by martinjuhasz** [twitter-fabric/velocity-react#154]
Is there a way to queue up multiple animations like vanilla Velocity does with calling it multiple times or chaining the promises?

I'd like to transform my css animation that is a multistep keyframe animation to a component and run this on mount.
```css
@keyframes dash {
  0%{
    stroke-dasharray: 1,200;
    stroke-dashoffset: 0;
  }
  50%{
    stroke-dasharray: 89,200;
    stroke-dashoffset: -35;
  }
  100%{
    stroke-dasharray: 89,200;
    stroke-dashoffset: -124;
  }
}
```
With Velocity i would just call it 3 times on the DOM object and give the last animation `loop: true` so that it runs infinitely. I know i can call `runAnimation` but with this i can't queue multiple different animations. I could probably change the components probs 3 times in a row, but this seems inelegant. Whats the best way to achive this with your components?
